[package]
name = "raymarcher"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
pollster = "0.2.5"
tokio = { version = "1", features = ["full"] }
